apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  labels:
    app: solar-system
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: solar-system
  type: NodePort
